version: "3.8"

services:
  telethon_app:
    image: telethon_img
    build: .
    command: python main.py
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy